# Generated by Django 3.1 on 2020-09-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.TextField(help_text='Provide address of a company')),
                ('company_started', models.DateTimeField(auto_now_add=True)),
                ('company_ended', models.DateTimeField(default='')),
                ('company_profit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(choices=[('cse', 'Computer science Engineering'), ('ece', 'Electronics and communication engineering')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_name', models.CharField(help_text='Provide employee Name', max_length=100)),
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('t', 'Transgender')], max_length=2)),
                ('employee_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee_address', models.TextField(help_text='Please provide address', null=True)),
            ],
        ),
    ]
