# Generated by Django 3.1 on 2020-09-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_with_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_ended',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
