# Generated by Django 3.1 on 2020-09-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_with_models', '0002_auto_20200904_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_ended',
            field=models.DateTimeField(),
        ),
    ]
